config/routes.rb
Rails.application.routes.draw do
  root "welcome#index"

  get "/login" => "sessions#new"
  resource  :session, only: [:create, :destroy]

  resources :users do
    member do
      get   "password"
      patch "password", action: "update_password"
      get   "confirm_delete"
    end

    resource  :quiz, only: [:show, :update]
    resource :personality, only: [:show, :update]
    get "/taste" => "tastes#show"
    resources :tastes, only: [:index]
  end

end

app/models/user.rb
class User < ActiveRecord::Base

  validates :name, presence: true
  validates :email, presence: true, uniqueness: true
  # for use with geocoder (this stuff may have to go into the session model instead)
  # can't be tested until the app is uploaded to heroku
  # geocoded_by :address
  # after_validation :geocode # auto-fetch coordinates

  # reverse_geocoded_by :latitude, :longitude
  # after_validation :reverse_geocode  # auto-fetch address

  has_secure_password

#determines if user role is admin
  def is_admin?
     (self.role =~ /admin/) == 0 ? true : false
  end

#sets role values
  def role_value
    case self.role
    when 'admin'      then 2
    when 'customer'   then 1
    else 0; end
  end

  # methods for use with geocoder, can't tell if they work until we are uploade to Heroku
  def get_location
    @street = request.location.street
    @city = request.location.city
    @state = request.location.state
    @country = request.location.country
  end

  def longitude
    request.location.longitude
  end

  def latitude
    request.location.latitude
  end

  def address
    [@street, @city, @state, @country].compact.join(', ')
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  before_action :authenticate,            except: [:new, :create]
  before_action :load_user,               except: [:index, :new, :create]
  before_action :authorize_admin_only,    only:   :index
  before_action :authorize_user_only,     only:   :show
  before_action :authorize_user_or_admin, except: [:index, :show, :new, :create]

  # GET /users
  # GET /users.json
  def index
    @users = User.all.sort.reverse.reject {|user| user == current_user}
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
    @user = User.find(params[:id])
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)
    @user.save
    # binding.pry
    user = User.find_by(name: user_params["name"])
    id = user.id
    redirect_to "/users/#{id}/quiz"

    # respond_to do |format|
    #   if @user.save
    #     format.html { redirect_to @user, notice: 'User was successfully created.' }
    #     format.json { render :show, status: :created, location: @user }
    #   else
    #     format.html { render :new }
    #     format.json { render json: @user.errors, status: :unprocessable_entity }
    #   end
    # end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:name, :email, :dob, :password, :password_confirmation)
    end

    def user_password_params
    @user_password_params ||= params.require(:user).permit(
      :old_password,
      :password,
      :password_confirmation
    )
  end

  def load_user
    @user = User.find_by(id: params[:id])
    redirect_to root_path if !@user
  end

  def authorize_admin_only
    unless current_user.is_admin?
      redirect_to user_path(current_user)
    end
  end

  def authorize_user_only
    unless current_user == @user
      redirect_to user_path(current_user)
    end
  end

  def authorize_user_or_admin
    unless current_user == @user || current_user.is_admin?
      redirect_to user_path(current_user)
    end
  end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>*<br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :email %>*<br>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :dob, 'Birthday' %><br>
    <%= f.date_field :dob %>
  </div>

  <% if !@user.persisted? # if we are creating instead of editing... %>
  <div class="field">
    <%= f.label :password %>*<br>
    <%= f.password_field :password %></br>
    <%= f.label :password_confirmation, 'Confirmation' %>*<br>
    <%= f.password_field :password_confirmation %></br>
  </div>

  <% else %>
    <div class="field">
    <%= f.label :password, 'Please re-enter your Password to make changes'%>*<br>
    <%= f.password_field :password %></br>
    <%= f.label :password_confirmation, 'Password Confirmation' %>*<br>
    <%= f.password_field :password_confirmation %></br>
  </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

<p>Fields with a * are mandatory.</p>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>
<%= render 'layouts/footer' %>

app/views/users/index.html.erb
<h1>Listing users</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th>Birthday</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.name %></td>
        <td><%= user.email %></td>
        <td><%= user.dob %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>
<%= render 'layouts/footer' %>

app/views/users/new.html.erb
<div class="mtndew">
  <div class="panel-heading">
    <h3 class="panel-title">Let's get started . . .</h3>
  </div>
  <div class="panel-body">
    <%= render 'form' %>

    <%= link_to 'Back', users_path %>
  </div>
</div>

<%= render 'layouts/footer' %>

app/views/users/show.html.erb
<div class="container">
  <div class="user_info">
    <h1><%= notice %></h1>
      <p>
        <strong>Name:</strong>
        <%= @user.name %>
      </p>

      <p>
        <strong>Email:</strong>
        <%= @user.email %>
      </p>

      <p>
        <strong>Birthday:</strong>
        <%= @user.dob %>
      </p>
  </div>

<div class="container-fluid">
<div class="jumbotron">
  <h2>Personality:</h2>
  <% id = @user.personality_id %>
  <% personality = Personality.find(id) %>
  <h1><a href="/users/<%= @user.id %>/personality"><%= personality.name %></a></h1>
</div>
</div>
</div>




<div class="container-fluid">
  <nav class="navbar navbar-default navbar-fixed-top" role="navigation">
  <%= link_to 'Home', root_path %> |
  <%= link_to 'Launch', user_taste_path(@user.id, personality.id) %> |
  <%= link_to 'Back', users_path %> |
  <%= link_to("Logout", session_path, method: :delete) %>
  </nav>

<%= link_to 'Go to your dashboard', user_taste_path(@user.id, personality.id) %> |
<%= link_to 'Back', users_path %>
<%= render 'layouts/footer' %>
</div>