config/routes.rb
Rails.application.routes.draw do
  root "welcome#index"

  get "/login" => "sessions#new"
  resource  :session, only: [:create, :destroy]

  resources :users do
    member do
      get   "password"
      patch "password", action: "update_password"
      get   "confirm_delete"
    end

    resource  :quiz, only: [:show, :update]
    resource :personality, only: [:show, :update]
    get "/taste" => "tastes#show"
    resources :tastes, only: [:index]
  end

end

app/models/taste.rb
class Taste < ActiveRecord::Base
  belongs_to :personality
  self.inheritance_column = :category

  validates :category, presence: true
  scope :do, -> { where(category: 'Do') }
  scope :eat, -> { where(category: 'Eat') }
  scope :go, -> { where(category: 'Go') }
  scope :listen, -> { where(category: 'Listen') }
  scope :read, -> { where(category: 'Read') }
  scope :shop, -> { where(category: 'Shop') }

  class << self
    def categories
      %w(Do Eat Go Listen Read Shop)
    end
  end

end

app/controllers/tastes_controller.rb
class TastesController < ApplicationController
  before_action :set_taste, only:  [:show]
  before_action :authorize_admin_only,    only: :index

  # GET /tastes
  # GET /tastes.json
  def index
    @tastes = Taste.all
  end

  # GET /tastes/1
  # GET /tastes/1.json
  def show
    user = User.find(params[:user_id])
    @personality = Personality.find(user.personality_id)
    @tastes = Taste.all
    wunderground_api
    case @personality.id
    when 1
      rss_feed_get(ESCAPE_ARTIST_URL)
      nyt_api(:escape_artist_query)
      instagram_api_eat
      instagram_api_shop
      instagram_api_go
    when 2
      rss_feed_get(INTELLIGENTSIA_URL)
      nyt_api(:intelligentsia_query)
      instagram_api_eat
      instagram_api_shop
      instagram_api_go
    when 3
      rss_feed_get(REALIST_RSS_URL)
      nyt_api(:realist_query)
      instagram_api_eat
      instagram_api_shop
      instagram_api_go
    when 4
      nyt_api(:sartorialist_query)
      rss_feed_get(SARTORIALIST_RSS_URL)
      instagram_api_eat
      instagram_api_shop
      instagram_api_go
    when 5
      nyt_api(:techie)
      meetup_api
      instagram_api_eat
      instagram_api_shop
      instagram_api_go
    end

    @tastes = @tastes.select{ |taste| taste.personality_id == @personality.id }
  end

  # GET /tastes/new
  def new
    @taste = Taste.new
  end

  # GET /tastes/1/edit
  def edit
  end

  # POST /tastes
  # POST /tastes.json
  def create
    @taste = Taste.new(taste_params)

    respond_to do |format|
      if @taste.save
        format.html { redirect_to @taste, notice: 'Taste was successfully created.' }
        format.json { render :show, status: :created, location: @taste }
      else
        format.html { render :new }
        format.json { render json: @taste.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tastes/1
  # PATCH/PUT /tastes/1.json
  def update
    respond_to do |format|
      if @taste.update(taste_params)
        format.html { redirect_to @taste, notice: 'Taste was successfully updated.' }
        format.json { render :show, status: :ok, location: @taste }
      else
        format.html { render :edit }
        format.json { render json: @taste.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tastes/1
  # DELETE /tastes/1.json
  def destroy
    @taste.destroy
    respond_to do |format|
      format.html { redirect_to tastes_url, notice: 'Taste was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_taste
      @taste = Taste.all
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def taste_params
      params.require(:taste).permit(:name)
    end

    def authorize_admin_only
      unless current_user.is_admin?
        redirect_to user_path(current_user)
      end
    end

    def authorize_user_only
      unless current_user == @user
        redirect_to user_path(current_user)
      end
    end

    def authorize_user_or_admin
      unless current_user == @user || current_user.is_admin?
        redirect_to user_path(current_user)
      end
    end
  end

app/helpers/tastes_helper.rb
module TastesHelper
end

app/views/tastes/_form.html.erb
<%= form_for(@taste) do |f| %>
  <% if @taste.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@taste.errors.count, "error") %> prohibited this taste from being saved:</h2>

      <ul>
      <% @taste.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/tastes/edit.html.erb
<h1>Editing taste</h1>

<%= render 'form' %>

<%= link_to 'Show', @taste %> |
<%= link_to 'Back', tastes_path %>
<%= render 'layouts/footer' %>

app/views/tastes/index.html.erb
<h1>Listing tastes</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @tastes.each do |taste| %>
      <tr>
        <td><%= taste.category %></td>
        <td><%= link_to 'Show', taste %></td>
        <td><%= link_to 'Edit', edit_taste_path(taste) %></td>
        <td><%= link_to 'Destroy', taste, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Taste', new_taste_path %>
<%= render 'layouts/footer' %>

app/views/tastes/new.html.erb
<h1>New taste</h1>

<%= render 'form' %>

<%= link_to 'Back', tastes_path %>
<%= render 'layouts/footer' %>

app/views/tastes/show-old.html.erb
<div class="container">

<%= notice %>

  <div class="page-header">
    <h1><%= @personality.name %>: <%= @personality.tags %></h1>
  </div>

  <% @tastes.each do |taste| %>

  <div class="row">

    <div class="col-sm-4">

      <% if taste.personality_id == @personality.id %>
      <%= taste.category %>
      <% case taste.category %>
      <% when "Eat" %>
          <img src="<%= @instagram_parsed_response_eat["data"][3]["images"]["standard_resolution"]["url"] %>" height="250" />
    </div>

    <div class="col-sm-4">
      <% when "Go" %>
        <img src="<%= @instagram_parsed_response_go["data"][3]["images"]["standard_resolution"]["url"] %>" height="250" />
    </div>

    <div class="col-sm-4">
      <% when "Shop" %>
        <img src="<%= @instagram_parsed_response_shop["data"][3]["images"]["standard_resolution"]["url"] %>" height="250" />
    </div>

    <div class="col-sm-4">
      <% when "Read" %>
        <% @nyt_parsed_response["results"].each do |book| %>
          <% book["book_details"].each do |info| %>
            <div class="books">
              <%= info["title"] %></br>
              <%= info["author"] %></br>
              <%= info["description"] %></br>
              <%= info["publisher"] %>
            </div>
          <% end %>
        <% end %>
    </div>
  </div>

  <div class="row">

    <div class="col-sm-4">
      <% when "Listen" %>
      <% case @personality.id %>
      <% when 1 %>
        <iframe src="https://embed.spotify.com/?uri=https://play.spotify.com/user/mobymus/playlist/7aBuRPft205uzpxsBxp3qS" width="300" height="380" frameborder="0" allowtransparency="true"></iframe>
    </div>

    <div class="col-sm-4">
      <% when 2 %>
        <iframe src="https://embed.spotify.com/?uri=https://play.spotify.com/user/soundrop/playlist/5Yibg8tyfrCKxHWzFIpFcN" width="300" height="380" frameborder="0" allowtransparency="true"></iframe>
    </div>

    <div class="col-sm-4">
      <% when 3 %>
        <iframe src="https://embed.spotify.com/?uri=https://play.spotify.com/user/sharemyplaylists.com/playlist/3KBBM9y2iNPVm8tVYmfmL9" width="300" height="380" frameborder="0" allowtransparency="true"></iframe>
    </div>

    <div class="col-sm-4">
      <% when 4 %>
        <iframe src="https://embed.spotify.com/?uri=https://play.spotify.com/user/sonymusicbelgium/playlist/6tnJ4g740KEorytHqqmmCU" width="300" height="380" frameborder="0" allowtransparency="true"></iframe>
    </div>
        <div class="col-sm-4">
          <% when 5 %>
            <iframe src="https://embed.spotify.com/?uri=https://play.spotify.com/user/12128193812/playlist/4DCIBYMQFR2IFXBqjDZJik" width="300" height="380" frameborder="0" allowtransparency="true"></iframe>
          <% end %>
        </div>
    </div>

    <div class="row">
      <div class="col-sm-4">
        <div class="books">
        <% when "Do" %>
          <% if @personality.id != 5 %>
              <%= @feed.channel.title %>
            <% @feed.items.each do |item| %>
                <%= item.title %>
            <% end %>
          </div>
        </div>
        <div class="col-sm-4">
          <% else %>
             <%= meetup["name"] %>
             <%= meetup["link"] %>
             <%= meetup["description"] %>
             <%= meetup["rating"] %>
             <% end %>
          <% end %>
        <% end %>
      <% end %>
    <% end %>
  </div>
  </div>


</div>
</div>

<div class="container-fluid">
  <nav class="navbar navbar-default navbar-fixed-top" role="navigation">
  <%= link_to 'Home', root_path %> |
  <%= link_to 'Back', users_path %> |
  <%= link_to("Logout", session_path, method: :delete) %>
  </nav>
</div>

</div> <!-- containter -->

app/views/tastes/show.html.erb
<div class="container">

<%= notice %>

  <div class="page-header">
    <h1><%= @personality.name %>: <%= @personality.tags %></h1>
  </div>

  <% @tastes.each do |taste| %>

    <div class="col-sm-4">
      <span id="taste-titles"><strong><%= taste.category %></strong></span></br>
      <% case taste.category %>
      <% when "Eat" %>
        <img src="<%= @instagram_parsed_response_eat["data"][3]["images"]["standard_resolution"]["url"] %>" height="350" width="350" />
      <% when "Go" %>
        <img src="<%= @instagram_parsed_response_go["data"][3]["images"]["standard_resolution"]["url"] %>" height="350" width="350" />
      <% when "Shop" %>
        <img src="<%= @instagram_parsed_response_shop["data"][3]["images"]["standard_resolution"]["url"] %>" height="350" width="350" />
      <% when "Read" %>
        <div class="scrollable">
          <% @nyt_parsed_response["results"].each do |book| %>
            <% book["book_details"].each do |info| %>
              <div>
                Title: <strong><%= info["title"] %></strong></br>
                Author: <%= info["author"] %></br>
                <%= info["description"] %></br>
              </div></br>
            <% end %>
          <% end %>
        </div>
      <% when "Listen" %>
        <% case @personality.id %>
        <% when 1 %>
          <iframe src="https://embed.spotify.com/?uri=https://play.spotify.com/user/mobymus/playlist/7aBuRPft205uzpxsBxp3qS" width="250" height="250" frameborder="0" allowtransparency="true"></iframe>
        <% when 2 %>
          <iframe src="https://embed.spotify.com/?uri=https://play.spotify.com/user/soundrop/playlist/5Yibg8tyfrCKxHWzFIpFcN" width="250" height="250" frameborder="0" allowtransparency="true"></iframe>
        <% when 3 %>
          <iframe src="https://embed.spotify.com/?uri=https://play.spotify.com/user/sharemyplaylists.com/playlist/3KBBM9y2iNPVm8tVYmfmL9" width="250" height="250" frameborder="0" allowtransparency="true"></iframe>
        <% when 4 %>
          <iframe src="https://embed.spotify.com/?uri=https://play.spotify.com/user/sonymusicbelgium/playlist/6tnJ4g740KEorytHqqmmCU" width="250" height="250" frameborder="0" allowtransparency="true"></iframe>
        <% when 5 %>
          <iframe src="https://embed.spotify.com/?uri=https://play.spotify.com/user/12128193812/playlist/4DCIBYMQFR2IFXBqjDZJik" width="250" height="250" frameborder="0" allowtransparency="true"></iframe>
        <% end %>
        <% when "Do" %>
        <div class="scrollable">
          <% if @personality.id != 5 %>
            <%= @feed.channel.title %>
            <ul><% @feed.items.each do |item| %>
              <li><%= item.title %></li></br>
            <% end %></ul>
          <% else %>
             <%= meetup["name"] %>
             <%= meetup["link"] %>
             <%= meetup["description"] %>
             <%= meetup["rating"] %>
          <% end %>
        </div>
      <% end %>
    </div>

  <% end %>

  <div class="container-fluid">
    <nav class="navbar navbar-default navbar-fixed-top" role="navigation">
    <%= link_to 'Home', root_path %> |
    <%= link_to 'Back', users_path %> |
    <%= link_to("Logout", session_path, method: :delete) %>
    </nav>
  </div>

</div> <!-- containter -->