config/routes.rb
Rails.application.routes.draw do
  root "welcome#index"

  get "/login" => "sessions#new"
  resource  :session, only: [:create, :destroy]

  resources :users do
    member do
      get   "password"
      patch "password", action: "update_password"
      get   "confirm_delete"
    end

    resource  :quiz, only: [:show, :update]
    resource :personality, only: [:show, :update]
    get "/taste" => "tastes#show"
    resources :tastes, only: [:index]
  end

end

app/models/personality.rb
class Personality < ActiveRecord::Base
  has_many :tastes
  delegate :do, :eat, :go, :listen, :read, :shop, to: :tastes
  self.inheritance_column = :name

  validates :name, presence: true
  scope :escape_artist, -> { where(name: 'EscapeArtist') }
  scope :intelligentsia, -> { where(name: 'Intelligentsia') }
  scope :realist, -> { where(name: 'Realist') }
  scope :sartorialist, -> { where(name: 'Sartorialist') }
  scope :techie, -> { where(name: 'Techie') }

  class << self
    def categories
      %w(EscapeArtist Intelligentsia Realist Sartorialist Techie)
    end
  end

end

app/controllers/personalities_controller.rb
class PersonalitiesController < ApplicationController
  before_action :set_personality, only: [:show, :edit, :update, :destroy]

  # GET /personalities
  # GET /personalities.json
  def index
    @personalities = Personality.all
  end

  # GET /personalities/1
  # GET /personalities/1.json
  def show
    @user = User.find(params[:user_id])
    @personality = Personality.find(@user.personality_id)
  end

  # GET /personalities/new
  def new
    @personality = Personality.new
  end

  # GET /personalities/1/edit
  def edit
  end

  # POST /personalities
  # POST /personalities.json
  def create
    @personality = Personality.new(personality_params)

    respond_to do |format|
      if @personality.save
        format.html { redirect_to @personality, notice: 'Personality was successfully created.' }
        format.json { render :show, status: :created, location: @personality }
      else
        format.html { render :new }
        format.json { render json: @personality.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /personalities/1
  # PATCH/PUT /personalities/1.json
  def update

    # respond_to do |format|
    #   if @personality.update(personality_params)
    #     format.html { redirect_to @personality, notice: 'Personality was successfully updated.' }
    #     format.json { render :show, status: :ok, location: @personality }
    #   else
    #     format.html { render :edit }
    #     format.json { render json: @personality.errors, status: :unprocessable_entity }
    #   end
    # end
  end

  # DELETE /personalities/1
  # DELETE /personalities/1.json
  def destroy
    @personality.destroy
    respond_to do |format|
      format.html { redirect_to personalities_url, notice: 'Personality was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_personality
      Personality.find_by(name: :answer)
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def personality_params
      params.require(:personality).permit(:name, :description)
    end
end

app/helpers/personalities_helper.rb
module PersonalitiesHelper
end

app/views/personalities/_form.html.erb
<%= form_for(@personality) do |f| %>
  <% if @personality.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@personality.errors.count, "error") %> prohibited this personality from being saved:</h2>

      <ul>
      <% @personality.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/personalities/edit.html.erb
<h1>Editing personality</h1>

<%= render 'form' %>

<%= link_to 'Show', @personality %> |
<%= link_to 'Back', personalities_path %>

app/views/personalities/index.html.erb
<h1>Listing personalities</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @personalities.each do |personality| %>
      <tr>
        <td><%= personality.name %></td>
        <td><%= personality.description %></td>
        <td><%= link_to 'Show', personality %></td>
        <td><%= link_to 'Edit', edit_personality_path(personality) %></td>
        <td><%= link_to 'Destroy', personality, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Personality', new_personality_path %>

app/views/personalities/new.html.erb
<h1>New personality</h1>

<%= render 'form' %>

<%= link_to 'Back', personalities_path %>

app/views/personalities/show.html.erb
<header>
  <%= link_to 'Home', root_path %>
</header>

<div class="container">
<h1 id="notice"><%= notice %></h1>


<div class="page-header">
  <h1><%= @personality.name %>: <%= @personality.tags %></h1>
</div>


<div class="container">
  <h3><%= @personality.description %></h3>
</div>


<div class="launch">
<button type="button" class="btn btn-default btn-lg"><%= link_to('Launch!', user_taste_path) %></button>
<p> Disagree with our assessment? <%= link_to("Retake the quiz
", user_quiz_path) %> </p>
</div>
</div>